---
- hosts: all
  become: yes
  tasks:

    - name: Install EPEL repo
      package:
        name:
          - epel-release


    - name: Install nginx
      package:
        name: 
          - nginx

    
    - name: backup existing config file
      command: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old
  
    - name: upload the nginx config file
      copy:
        src: "{{ configurationFileNginx }}"
        dest: /etc/nginx/nginx.conf
    


    - name: Start nginx
      service:
        name: nginx
        enabled: yes
        state: started


