---
- hosts: all
  become: yes
  tasks:
    - name: Install EPEL repo
      package:
        name: 
          - epel-release

    - name: Install nginx
      package:
        name: 
          - nginx

    - name: Start nginx
      service:
        name: nginx
        enabled: yes
        state: started