---
- hosts: all
  become: yes
  tasks:
    - name: upload the nginx-lb config file
      copy:
        src: "{{ configurationFile }}"

        dest: /etc/nginx/nginx.conf

    - name: Start nginx
      service:
        name: nginx
        enabled: yes
        state: started

